services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: vendor-payments-api

    ports:
      - "8000:8000"

    env_file:
      - .env

    environment:
      PORT: 8000

    volumes:
      - ${USERPROFILE}/.aws:/root/.aws:ro

    restart: unless-stopped